# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('p', 'Pay'), ('a', 'Allowance'), ('d', 'Deduction')], max_length=2, verbose_name='Type')),
                ('value', models.IntegerField(verbose_name='Default Value')),
                ('isPercentage', models.BooleanField(verbose_name='Percentage')),
                ('isApplicable', models.BooleanField(verbose_name='Applicable')),
                ('isOptional', models.BooleanField(verbose_name='Optional')),
                ('paymentType', models.CharField(choices=[('y', 'Yearly'), ('hy', 'Half Yearly'), ('m', 'Monthly'), ('o', 'One Time')], default='m', max_length=2, verbose_name='Payment Type')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAllowanceDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('isPercentage', models.BooleanField()),
                ('isApplicable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SalaryScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_no', models.IntegerField()),
                ('class_type', models.IntegerField(choices=[(1, 'First Class'), (2, 'Second Class'), (3, 'Third Class'), (4, 'Fourth Class')])),
            ],
        ),
        migrations.CreateModel(
            name='SalarySheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFreezed', models.BooleanField(default=False)),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('modified_date', models.DateField(default=django.utils.timezone.now, verbose_name='Modified At')),
            ],
        ),
        migrations.CreateModel(
            name='SalarySheetDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('allowance_deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AllowanceDeduction')),
                ('salary_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SalarySheet')),
            ],
        ),
        migrations.AddField(
            model_name='salarysheet',
            name='allowance_deductions',
            field=models.ManyToManyField(through='account.SalarySheetDetails', to='account.AllowanceDeduction'),
        ),
    ]
