# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarysheet',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='salaryscale',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Designation'),
        ),
        migrations.AddField(
            model_name='salaryscale',
            name='starting_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SalaryScale'),
        ),
        migrations.AddField(
            model_name='employeeallowancededuction',
            name='allowance_deduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AllowanceDeduction'),
        ),
        migrations.AddField(
            model_name='employeeallowancededuction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
    ]
