# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160623_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancededuction',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allowancededuction',
            name='modified_at',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeallowancededuction',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeallowancededuction',
            name='modified_at',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='employeeallowancededuction',
            unique_together=set([('employee', 'allowance_deduction')]),
        ),
    ]
