# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160624_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarysheet',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarysheet',
            name='modified_at',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now, verbose_name='Modified At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarysheetdetails',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarysheetdetails',
            name='modified_at',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now, verbose_name='Modified At'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allowancededuction',
            name='modified_at',
            field=models.DateField(auto_now=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='employeeallowancededuction',
            name='modified_at',
            field=models.DateField(auto_now=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='employeeallowancededuction',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
