# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20160626_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeallowancededuction',
            name='isApplicable',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='employeeallowancededuction',
            name='isPercentage',
            field=models.BooleanField(),
        ),
    ]
