# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20160626_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancededuction',
            name='code',
            field=models.CharField(max_length=3, null=True, verbose_name='Code'),
        ),
    ]
