# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_allowancededuction_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_no', models.IntegerField(verbose_name='Grade')),
                ('description', models.TextField(blank='True', null=True, verbose_name='Description')),
                ('employee_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.EmployeeClass', verbose_name='Employee Category')),
            ],
        ),
        migrations.CreateModel(
            name='GradeStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('isStarting', models.BooleanField()),
                ('nextStep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.GradeStep')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='steps',
            field=models.ManyToManyField(to='account.GradeStep', verbose_name='Steps'),
        ),
    ]
