# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20160702_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryscale',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='salaryscale',
            name='starting_step',
        ),
        migrations.AlterField(
            model_name='grade',
            name='employee_class',
            field=models.CharField(choices=[('fi', 'First Class'), ('se', 'Second Class'), ('th', 'Third Class'), ('fo', 'Fourth Class')], max_length=2),
        ),
        migrations.DeleteModel(
            name='EmployeeClass',
        ),
        migrations.DeleteModel(
            name='SalaryScale',
        ),
    ]
