# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20160702_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(blank='True', null=True, verbose_name='Description')),
            ],
        ),
        migrations.AlterModelOptions(
            name='allowancededuction',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='allowancededuction',
            name='isOptional',
        ),
        migrations.AddField(
            model_name='allowancededuction',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='allowancededuction',
            name='category',
            field=models.CharField(choices=[('', '----'), ('p', 'Pay'), ('a', 'Allowance'), ('d', 'Deduction')], max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='employee_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.EmployeeClass', verbose_name='Class'),
        ),
    ]
