# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20160703_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceDeductionEmployeeClassValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='salarysheet',
            name='date',
            field=models.DateField(null=True, verbose_name='Month Ending'),
        ),
        migrations.AddField(
            model_name='salarysheet',
            name='isWithdrawan',
            field=models.BooleanField(default=False, verbose_name='Withdrawn'),
        ),
        migrations.RemoveField(
            model_name='allowancededuction',
            name='value',
        ),
        migrations.AddField(
            model_name='allowancedeductionemployeeclassvalue',
            name='allowance_deduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AllowanceDeduction'),
        ),
        migrations.AddField(
            model_name='allowancedeductionemployeeclassvalue',
            name='employee_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.EmployeeClass'),
        ),
        migrations.AddField(
            model_name='allowancededuction',
            name='value',
            field=models.ManyToManyField(through='account.AllowanceDeductionEmployeeClassValue', to='account.EmployeeClass'),
        ),
    ]
