# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 17:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20160704_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeclass',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 7, 4, 17, 44, 32, 368537, tzinfo=utc), verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeclass',
            name='modified_at',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 7, 4, 17, 44, 36, 293761, tzinfo=utc), verbose_name='Modified At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 7, 4, 17, 44, 40, 180984, tzinfo=utc), verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='modified_at',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 7, 4, 17, 44, 45, 705300, tzinfo=utc), verbose_name='Modified At'),
            preserve_default=False,
        ),
    ]
