# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 04:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20160704_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarysheetdetails',
            name='comment',
        ),
        migrations.AddField(
            model_name='salarysheet',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeallowancededuction',
            name='allowance_deduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.AllowanceDeduction'),
        ),
        migrations.AlterField(
            model_name='employeeallowancededuction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='salarysheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 7, 31, 4, 8, 37, 173088, tzinfo=utc), verbose_name='Month Ending'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salarysheetdetails',
            name='allowance_deduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.AllowanceDeduction'),
        ),
    ]
