# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20160731_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowancededuction',
            old_name='isApplicable',
            new_name='is_applicable',
        ),
        migrations.RenameField(
            model_name='allowancededuction',
            old_name='isPercentage',
            new_name='is_percentage',
        ),
        migrations.RenameField(
            model_name='allowancededuction',
            old_name='paymentType',
            new_name='payment_type',
        ),
        migrations.RenameField(
            model_name='employeeallowancededuction',
            old_name='isApplicable',
            new_name='is_applicable',
        ),
        migrations.RenameField(
            model_name='employeeallowancededuction',
            old_name='isPercentage',
            new_name='is_percentage',
        ),
        migrations.RenameField(
            model_name='salarysheet',
            old_name='isFreezed',
            new_name='is_freezed',
        ),
        migrations.RenameField(
            model_name='salarysheet',
            old_name='isWithdrawan',
            new_name='is_withdrawan',
        ),
    ]
