# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20160731_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowancedeductionemployeeclassvalue',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='employeeallowancededuction',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='salarysheetdetails',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
