# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20160802_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowancedeductionemployeeclassvalue',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='employeeallowancededuction',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salarysheetdetails',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
