# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 05:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('ac', 'Academic'), ('ad', 'Administrative')], default='ac', max_length=2, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('f', 'First Class'), ('s', 'Second Class'), ('t', 'Third Class')], default='f', max_length=2, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank='', default='', verbose_name='Address')),
                ('tax_id_number', models.CharField(max_length=20, null=True, verbose_name='Tax ID')),
                ('account_number', models.CharField(max_length=20, null=True, verbose_name='Account Number')),
                ('joining_date', models.DateField(null=True, verbose_name='Joining Date')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1, verbose_name='Gender')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('modified_at', models.DateField(default=django.utils.timezone.now, verbose_name='Modified At')),
                ('allowance_deductions', models.ManyToManyField(through='account.EmployeeAllowanceDeduction', to='account.AllowanceDeduction')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Department', verbose_name='Department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Designation', verbose_name='Designation')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeIncrement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Increment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField()),
                ('resigning_date', models.DateField(null=True)),
                ('isActive', models.BooleanField()),
                ('comment', models.TextField()),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Designation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='employeeincrement',
            name='increment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Increment'),
        ),
        migrations.AddField(
            model_name='employee',
            name='increments',
            field=models.ManyToManyField(through='employee.EmployeeIncrement', to='employee.Increment'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
    ]
