# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20160623_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='modified_at',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now, verbose_name='Modified At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designation',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designation',
            name='modified_at',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now, verbose_name='Modified At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeincrement',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeincrement',
            name='modified_at',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now, verbose_name='Modified At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='increment',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='increment',
            name='modified_at',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now, verbose_name='Modified At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workhistory',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workhistory',
            name='modified_at',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now, verbose_name='Modified At'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='modified_at',
            field=models.DateField(auto_now=True, verbose_name='Modified At'),
        ),
    ]
