# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20160624_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='acronym',
            field=models.CharField(max_length=10, null=True, verbose_name='Acronym'),
        ),
    ]
