# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20160626_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('ac', 'Academic'), ('ad', 'Administrative')], max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='type',
            field=models.CharField(choices=[('f', 'First Class'), ('s', 'Second Class'), ('t', 'Third Class')], max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
    ]
