# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20160702_1330'),
        ('employee', '0006_auto_20160627_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='type',
        ),
        migrations.AddField(
            model_name='designation',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Grade'),
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.CharField(choices=[('t', 'Teacher'), ('o', 'Officer'), ('s', 'Stuff')], default='t', max_length=1, verbose_name='Category'),
        ),
    ]
