# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20160731_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workhistory',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
    ]
