# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0009_auto_20160731_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLogForGPF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction', models.IntegerField(default=0, verbose_name='Deduction')),
                ('interest', models.IntegerField(default=0, verbose_name='Interest')),
                ('date', models.DateField(verbose_name='Month Ending')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
            ],
        ),
        migrations.CreateModel(
            name='ProvidentFundProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasInterest', models.BooleanField(verbose_name='Interest Taken')),
                ('percentage', models.IntegerField(default=0, verbose_name='Percentage')),
                ('credit', models.IntegerField(default=0, verbose_name='Credit')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='monthlylogforgpf',
            name='providentFundProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provident_fund.ProvidentFundProfile'),
        ),
    ]
