# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provident_fund', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlylogforgpf',
            old_name='providentFundProfile',
            new_name='provident_fund_profile',
        ),
        migrations.RenameField(
            model_name='providentfundprofile',
            old_name='hasInterest',
            new_name='has_Interest',
        ),
    ]
