# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provident_fund', '0002_auto_20160731_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providentfundprofile',
            old_name='has_Interest',
            new_name='has_interest',
        ),
        migrations.RemoveField(
            model_name='monthlylogforgpf',
            name='deduction',
        ),
        migrations.AddField(
            model_name='monthlylogforgpf',
            name='subscription',
            field=models.IntegerField(default=0, verbose_name='Subscription'),
        ),
        migrations.AlterField(
            model_name='monthlylogforgpf',
            name='provident_fund_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provident_fund.ProvidentFundProfile', verbose_name='Employee'),
        ),
    ]
