# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provident_fund', '0004_auto_20160802_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlylogforgpf',
            name='interest',
            field=models.FloatField(default=0, verbose_name='Interest'),
        ),
        migrations.AlterField(
            model_name='monthlylogforgpf',
            name='subscription',
            field=models.FloatField(default=0, verbose_name='Subscription'),
        ),
        migrations.AlterField(
            model_name='providentfundprofile',
            name='credit',
            field=models.FloatField(default=0, verbose_name='Credit'),
        ),
    ]
