# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provident_fund', '0005_auto_20160802_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providentfundprofile',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee', unique=True),
        ),
    ]
