# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provident_fund', '0006_auto_20160804_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providentfundprofile',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee'),
        ),
    ]
