# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-06 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provident_fund', '0007_auto_20160804_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlylogforgpf',
            name='provident_fund_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provident_fund.ProvidentFundProfile', verbose_name='Employee'),
        ),
    ]
